# Generated by Django 5.2.4 on 2025-08-11 14:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_horario_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='updated_at',
            new_name='fecha_actualizacion',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='fecha_subida',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='cupos_disponibles',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='material',
            name='es_obligatorio',
        ),
        migrations.RemoveField(
            model_name='material',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='material',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='material',
            name='url',
        ),
        migrations.AddField(
            model_name='horario',
            name='aula',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Aula'),
        ),
        migrations.AddField(
            model_name='horario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='instructor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instructor'),
        ),
        migrations.AddField(
            model_name='material',
            name='enlace_externo',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace externo'),
        ),
        migrations.AddField(
            model_name='material',
            name='nombre',
            field=models.CharField(default='Material sin nombre', max_length=200, verbose_name='Nombre del material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='tipo_material',
            field=models.CharField(choices=[('documento', 'Documento'), ('video', 'Video'), ('presentacion', 'Presentación'), ('enlace', 'Enlace'), ('imagen', 'Imagen'), ('otro', 'Otro')], default='documento', max_length=20, verbose_name='Tipo de material'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Curso activo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código del curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracion_horas',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración en horas'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('mixta', 'Mixta')], default='presencial', max_length=20, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del curso'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='cursos.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia_semana',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10, verbose_name='Día de la semana'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_fin',
            field=models.TimeField(verbose_name='Hora de fin'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='material',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='materiales/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='cursos.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='material',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('curso', 'dia_semana', 'hora_inicio')},
        ),
        migrations.DeleteModel(
            name='Inscripcion',
        ),
    ]
